export const AVAILABLE_COMMANDS = [
  "Mirror Website",
  "Convert Links",
  "Adjust Extension",
  "Page Requisites",
  "No Parent Directory",
  "Limit Download Rate",
  "Wait Between Downloads",
  "Random Wait Time",
  "Follow All Links",
  "Follow FTP Links",
  "Use Content Disposition",
  "Continue Interrupted Downloads",
  "Spider Mode (Check Only)",
  "Use File Timestamping",
  "Debug Mode",
  "HTTPS Only",
  "Ignore Robots.txt",
  "Backup Converted Files",
  "Delete After Download",
  "Stay in Same Domain",
  "Log Only Errors",
  "Verify SSL Certificate",
  "No Verbose Output",
  "Show Progress Bar",
  "Retry on Connection Refused",
  "No File Overwriting",
  "Input File List",
  "Number of Retries",
  "Connection Timeout",
  "Run in Background",
  "Directory Prefix",
  "No Host Directories",
  "Skip Directory Levels"
];

export const commandToFlag: { [key: string]: string } = {
  "Mirror Website": "--mirror",
  "Convert Links": "--convert-links",
  "Adjust Extension": "--adjust-extension",
  "Page Requisites": "--page-requisites",
  "No Parent Directory": "--no-parent",
  "Limit Download Rate": "--limit-rate",
  "Wait Between Downloads": "--wait",
  "Random Wait Time": "--random-wait",
  "Follow All Links": "--follow-links",
  "Follow FTP Links": "--follow-ftp",
  "Use Content Disposition": "--content-disposition",
  "Continue Interrupted Downloads": "--continue",
  "Spider Mode (Check Only)": "--spider",
  "Use File Timestamping": "--timestamping",
  "Debug Mode": "--debug",
  "HTTPS Only": "--https-only",
  "Ignore Robots.txt": "--ignore-robots",
  "Backup Converted Files": "--backup-converted",
  "Delete After Download": "--delete-after",
  "Stay in Same Domain": "--span-hosts",
  "Log Only Errors": "--quiet",
  "Verify SSL Certificate": "--secure-protocol",
  "No Verbose Output": "--no-verbose",
  "Show Progress Bar": "--show-progress",
  "Retry on Connection Refused": "--retry-connrefused",
  "No File Overwriting": "--no-clobber",
  "Input File List": "--input-file",
  "Number of Retries": "--tries",
  "Connection Timeout": "--timeout",
  "Run in Background": "--background",
  "Directory Prefix": "--directory-prefix",
  "No Host Directories": "--no-host-directories",
  "Skip Directory Levels": "--cut-dirs"
};

export const flagToCommand = Object.entries(commandToFlag).reduce((acc, [key, value]) => {
  acc[value] = key;
  return acc;
}, {} as { [key: string]: string });