export const AVAILABLE_COMMANDS = [
  "Mirror Website",
  "Follow Links",
  "Convert Links",
  "Adjust Extensions",
  "No Clobber",
  "Include Parents",
  "Follow FTP",
  "Content Disposition",
  "Continue Transfer",
  "Spider Mode",
  "Use Timestamping",
  "Debug Mode",
  "Page Requisites",
  "HTTPS Only",
  "Random Wait",
  "Ignore Robots",
  "Backup Converted",
  "Delete After",
  "Same Domain Only",
  "Log Only Errors",
  "Verify SSL",
  "Continue Download"
];