export const AVAILABLE_COMMANDS = [
  "Limit Download Rate",
  "Wait Between Downloads",
  "Random Wait Time",
  "Directory Prefix",
  "No Host Directories",
  "Skip Directory Levels",
  "HTTP Username",
  "HTTP Password",
  "Skip Authentication Challenge",
  "FTP Username",
  "FTP Password",
  "Keep FTP Listing",
  "Input File List",
  "Continue Interrupted Downloads",
  "No File Overwriting",
  "Enable Recursive Download",
  "No Parent Directory",
  "Reject File Patterns",
  "Maximum Depth Level",
  "Download Page Requirements",
  "Add HTML Extension",
  "Convert Links for Local Viewing",
  "Restrict Filenames",
  "Allowed Domains",
  "Accept File Types",
  "No Directory Structure",
  "Mirror Website",
  "Convert Links",
  "Adjust Extension",
  "Page Requisites",
  "Follow All Links",
  "Follow FTP Links",
  "Use Content Disposition",
  "Spider Mode (Check Only)",
  "Use File Timestamping",
  "Debug Mode",
  "HTTPS Only",
  "Ignore Robots.txt",
  "Backup Converted Files",
  "Delete After Download",
  "Stay in Same Domain",
  "Log Only Errors",
  "Verify SSL Certificate",
  "No Verbose Output",
  "Show Progress Bar",
  "Retry on Connection Refused",
  "Number of Retries",
  "Connection Timeout",
  "Run in Background"
];

export const commandToFlag: { [key: string]: string } = {
  "Limit Download Rate": "--limit-rate",
  "Wait Between Downloads": "--wait",
  "Random Wait Time": "--random-wait",
  "Directory Prefix": "--directory-prefix",
  "No Host Directories": "--no-host-directories",
  "Skip Directory Levels": "--cut-dirs",
  "HTTP Username": "--http-user",
  "HTTP Password": "--http-password",
  "Skip Authentication Challenge": "--auth-no-challenge",
  "FTP Username": "--ftp-user",
  "FTP Password": "--ftp-password",
  "Keep FTP Listing": "--no-remove-listing",
  "Input File List": "--input-file",
  "Continue Interrupted Downloads": "--continue",
  "No File Overwriting": "--no-clobber",
  "Enable Recursive Download": "--recursive",
  "No Parent Directory": "--no-parent",
  "Reject File Patterns": "--reject",
  "Maximum Depth Level": "--level",
  "Download Page Requirements": "--page-requisites",
  "Add HTML Extension": "--html-extension",
  "Convert Links for Local Viewing": "--convert-links",
  "Restrict Filenames": "--restrict-file-names",
  "Allowed Domains": "--domains",
  "Accept File Types": "--accept",
  "No Directory Structure": "--no-directories",
  "Mirror Website": "--mirror",
  "Convert Links": "--convert-links",
  "Adjust Extension": "--adjust-extension",
  "Page Requisites": "--page-requisites",
  "Follow All Links": "--follow-links",
  "Follow FTP Links": "--follow-ftp",
  "Use Content Disposition": "--content-disposition",
  "Spider Mode (Check Only)": "--spider",
  "Use File Timestamping": "--timestamping",
  "Debug Mode": "--debug",
  "HTTPS Only": "--https-only",
  "Ignore Robots.txt": "--ignore-robots",
  "Backup Converted Files": "--backup-converted",
  "Delete After Download": "--delete-after",
  "Stay in Same Domain": "--span-hosts",
  "Log Only Errors": "--quiet",
  "Verify SSL Certificate": "--secure-protocol",
  "No Verbose Output": "--no-verbose",
  "Show Progress Bar": "--show-progress",
  "Retry on Connection Refused": "--retry-connrefused",
  "Number of Retries": "--tries",
  "Connection Timeout": "--timeout",
  "Run in Background": "--background"
};

export const flagToCommand = Object.entries(commandToFlag).reduce((acc, [key, value]) => {
  acc[value] = key;
  return acc;
}, {} as { [key: string]: string });