import { useState } from "react";
import { WgetOptions } from "@/types/wget";

const defaultOptions: WgetOptions = {
  url: "",
  recursive: false,
  maxDepth: 5,
  waitTime: 0,
  followLinks: true,
  includePattern: "",
  excludePattern: "",
  saveDirectory: "",
  fileTypes: [],
  excludeFileTypes: [],
  includeParents: true,
  userAgent: "",
  limitRate: "",
  outputFile: "",
  logFile: "",
  username: "",
  password: "",
  cookieFile: "",
  saveCookies: false,
  retries: 0,
  timeout: 0,
  continueDownload: true,
  noHostDirs: false,
  cutDirs: 0,
  noClobber: true,
  debug: false,
  convertLinks: false,
  adjustExtension: true,
  proxyEnabled: false,
  proxyUser: "",
  proxyPass: "",
  timestamping: false,
  randomWait: false,
  httpsOnly: false,
  ignoreRobots: false,
  backupConverted: false,
  deleteAfter: false,
  tempFile: false,
  maxFileSize: "",
  minFileSize: "",
  rejectRegex: "",
  recursionLevel: 5,
  sameDomain: false,
  domains: "",
  excludeDomains: "",
  httpsProxy: "",
  noCheckCertificate: false,
  caCertificate: "",
  parallelDownloads: 1,
  connectionLimit: "",
  logOnlyErrors: false,
  followFtp: false,
  contentDisposition: false,
  continueTransfer: false,
  mirror: false,
  spiderMode: false,
  pageRequisites: false,
  verifySSL: true,
};

export const useWgetOptions = () => {
  const [options, setOptions] = useState<WgetOptions>(defaultOptions);
  return { options, setOptions };
};